# Generated by Django 2.2.6 on 2020-04-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='does_livestock',
            field=models.BooleanField(default=False),
        ),
    ]
