# Generated by Django 2.2.6 on 2020-04-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='This product is very nice', max_length=500),
            preserve_default=False,
        ),
    ]
