# Generated by Django 2.2.6 on 2020-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
