# Generated by Django 2.2.6 on 2020-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_on_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
