# Generated by Django 2.2.6 on 2020-05-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200517_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reference_code',
            new_name='im_reference_code',
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
