# Generated by Django 2.2.6 on 2020-05-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200518_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='aseyin', max_length=200),
            preserve_default=False,
        ),
    ]
